name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/Gamperaliya.jpg
    - assets/Kaliyugaya.jpg
    - assets/Malaunge_Aurudu_Da.jpg
    - assets/Chathurarya_Sathya.jpg
    - assets/GURU_GEETHAYA.jpg
    - assets/Ape_gama.jpg
    - assets/Madol_duwa.jpg
    - assets/Senkottan.jpg
    - assets/Malagiya_aththo.jpg
    - assets/Baddegame.jpg

  uses-material-design: true
